# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1

checkpoint:
  save_interval: 1
  keep_last_epochs: 5
  keep_best_checkpoints: 5
  best_checkpoint_metric: dec_accuracy
  maximize_best_checkpoint_metric: true
  restore_file: checkpoint_last.pt

distributed_training:
  ddp_backend: legacy_ddp
  find_unused_parameters: true
  distributed_world_size: 1
  distributed_port: -1
  nprocs_per_node: 8

task:
  _name: joint_sc2t_pretraining
  data: ???
  fine_tuning: true
  label_dir: ???
  normalize: false  # must be consistent with pre-training
  labels: ???
  store_labels: true
  single_target: true
  add_decoder_target: true
  pad_audio: false
  random_crop: true
  hubert_tokenizer: "none"
  sp_path: None

dataset:
  num_workers: 0
  max_tokens: 800000
  skip_invalid_size_inputs_valid_test: true
  train_subset: train_100
  valid_subset: dev_other
  required_batch_size_multiple: 1
  grouped_shuffling: true

criterion:
  _name: ctc_ce
  zero_infinity: true
  label_smoothing: 0.2
  dec_weight: 0.8

optimization:
  max_update: 100000
  lr: [0.00003]
  clip_norm: 1.0
  sentence_avg: false
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  weight_decay: 0.0

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 5000

model:
  _name: speechut_asr
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.5
  mask_channel_prob: 0
  activation_dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 1.0
  freeze_finetune_updates: 0
  add_decoder: true

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
